'use client';

import { useState } from 'react';
import { TravelData } from '@/types/travel';
import CityInput from '@/components/CityInput';
import TravelCard from '@/components/TravelCard';
import SectionWrapper from '@/components/SectionWrapper';
import LoadingSpinner from '@/components/LoadingSpinner';
import { Map, Bus, Lightbulb, AlertCircle, Plane, Sparkles } from 'lucide-react';

export default function Home() {
  const [data, setData] = useState<TravelData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSearch = async (city: string) => {
    setLoading(true);
    setError(null);
    setData(null);

    try {
      const response = await fetch('/api/travel', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ city }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to fetch travel guide.');
      }

      setData(result.data);
    } catch (err: any) {
      setError(err.message || 'An unexpected error occurred.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen relative overflow-hidden">
      {/* Decorative Blobs */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden -z-10 pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-96 h-96 bg-purple-300 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob"></div>
        <div className="absolute top-[-10%] right-[-10%] w-96 h-96 bg-yellow-200 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob animation-delay-2000"></div>
        <div className="absolute -bottom-32 left-20 w-96 h-96 bg-pink-300 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-blob animation-delay-4000"></div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24 space-y-16">
        {/* Hero Section */}
        <div className="text-center space-y-8 relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/50 backdrop-blur-md border border-white/60 shadow-sm text-slate-600 font-medium text-sm animate-in fade-in slide-in-from-top-4 duration-700">
            <Sparkles className="w-4 h-4 text-amber-500" />
            <span>AI-Powered Local Insights</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-slate-900 animate-in fade-in slide-in-from-bottom-4 duration-1000">
            Explore the World <br className="hidden md:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-violet-600">
              Like a Local
            </span>
          </h1>

          <p className="text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200">
            Discover hidden gems, historical landmarks, and smart travel tips for any city, instantly generated by AI.
          </p>

          <div className="pt-4 animate-in fade-in slide-in-from-bottom-12 duration-1000 delay-300">
            <CityInput onSearch={handleSearch} isLoading={loading} />
          </div>
        </div>

        {/* Error State */}
        {error && (
          <div className="max-w-2xl mx-auto animate-in fade-in slide-in-from-top-4">
            <div className="bg-red-50/80 backdrop-blur-sm border border-red-200/60 rounded-2xl p-4 flex items-center gap-4 text-red-700 shadow-lg shadow-red-500/5">
              <div className="p-2 bg-red-100 rounded-full">
                <AlertCircle className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-semibold">Something went wrong</h3>
                <p className="text-sm opacity-90">{error}</p>
              </div>
            </div>
          </div>
        )}

        {/* Loading State */}
        {loading && <LoadingSpinner />}

        {/* Results Section */}
        {data && !loading && (
          <div className="space-y-12 animate-in fade-in slide-in-from-bottom-12 duration-700">

            {/* City Overview */}
            <SectionWrapper title="Overview" icon={<Map className="w-5 h-5 text-white" />} gradient="from-blue-500 to-cyan-500">
              <p className="text-lg text-slate-700 leading-relaxed">
                {data.city_overview}
              </p>
            </SectionWrapper>

            {/* Tourist Places */}
            <section className="space-y-6">
              <div className="flex items-center gap-3 px-2">
                <div className="p-2 bg-gradient-to-br from-violet-500 to-fuchsia-500 rounded-lg text-white shadow-lg shadow-violet-500/20">
                  <Plane className="w-5 h-5" />
                </div>
                <h2 className="text-2xl md:text-3xl font-bold text-slate-800">Must-Visit Places</h2>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {data.tourist_places.map((place, index) => (
                  <div key={index} className="animate-in fade-in slide-in-from-bottom-8 duration-700" style={{ animationDelay: `${index * 100}ms` }}>
                    <TravelCard place={place} />
                  </div>
                ))}
              </div>
            </section>

            {/* Local Transport & Tips Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <SectionWrapper title="Local Transportation" icon={<Bus className="w-5 h-5 text-white" />} gradient="from-emerald-500 to-teal-500" className="h-full">
                <p className="text-slate-700 leading-relaxed whitespace-pre-line">
                  {data.local_transport}
                </p>
              </SectionWrapper>

              <SectionWrapper title="Smart Local Tips" icon={<Lightbulb className="w-5 h-5 text-white" />} gradient="from-amber-500 to-orange-500" className="h-full">
                <p className="text-slate-700 leading-relaxed whitespace-pre-line">
                  {data.smart_tips}
                </p>
              </SectionWrapper>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
